// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRNeS0mbTiUgnBqIJ_UyVEfyXiMsVb-i8',
    appId: '1:984485862980:web:8a2a3eabb2e931ec6ee611',
    messagingSenderId: '984485862980',
    projectId: 'angostura-digital',
    authDomain: 'angostura-digital.firebaseapp.com',
    storageBucket: 'angostura-digital.firebasestorage.app',
    measurementId: 'G-1HM04MCP3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvpkgT-bEcgXbpH9DnTi_9SburnoYzUQQ',
    appId: '1:984485862980:android:ebd6750923d1b5b06ee611',
    messagingSenderId: '984485862980',
    projectId: 'angostura-digital',
    storageBucket: 'angostura-digital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZZ3pRx57JWlbtzWyhIIVFeqL2BxyeEk',
    appId: '1:984485862980:ios:e1cc03cf385021bc6ee611',
    messagingSenderId: '984485862980',
    projectId: 'angostura-digital',
    storageBucket: 'angostura-digital.firebasestorage.app',
    iosBundleId: 'com.example.angosturaDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqZZ3pRx57JWlbtzWyhIIVFeqL2BxyeEk',
    appId: '1:984485862980:ios:e1cc03cf385021bc6ee611',
    messagingSenderId: '984485862980',
    projectId: 'angostura-digital',
    storageBucket: 'angostura-digital.firebasestorage.app',
    iosBundleId: 'com.example.angosturaDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRNeS0mbTiUgnBqIJ_UyVEfyXiMsVb-i8',
    appId: '1:984485862980:web:683bbeed4c53dae56ee611',
    messagingSenderId: '984485862980',
    projectId: 'angostura-digital',
    authDomain: 'angostura-digital.firebaseapp.com',
    storageBucket: 'angostura-digital.firebasestorage.app',
    measurementId: 'G-JG02LZ9ZF6',
  );
}
