name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

# Esto soluciona la advertencia de Node.js 20 para el futuro (Junio 2026)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Instalar Flutter en el servidor de GitHub
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Acelera futuros despliegues

      # 2. Descargar librerías y COMPILAR la app
      - name: Build Web App
        run: |
          flutter pub get
          flutter build web --release

      # 3. Desplegar a Firebase
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGOSTURA_DIGITAL }}
          channelId: live
          projectId: angostura-digital
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks # <--- AGREGA ESTA LÍNEA